### ISSUE TITLE
I made Streamly go FFI

### ISSUE THREAD

**Issue by sgonyea** [brianmario/streamly#2]
I figured I should notify you about it and see if you care / whichever :).

https://github.com/aitrus/streamly_ffi

I replaced your C Extension with an FFI layer.  It benchmarks pretty favorably, so far.  Then again, I haven't yet added the error checking or any of that nonsense.

Benchmarks:

https://gist.github.com/670362

**Comment by sgonyea** [comment]
Oh, so I can turn that into a Pull request or .. yeah.

**Comment by sgonyea** [comment]
Damn it, Comment and Close.  Why are you closer than Comment?

**Comment by brianmario** [comment]
Yeah a pull request would be awesome. I'd like to use that to start a dialog about how we could merge your FFI stuff to work along side the C extension (for platforms that can't use the C extension like jRuby). Maybe under a Streamly::FFI namespace or something that we could fallback the Streamly.get/post/etc API methods to if the C extension isn't available.
